[alias]
xtask = "run -p alvr_xtask --"

[build]
# This is just for the android build. This isn't actually needed unless the default target dir has
# been changed system-wise
target-dir = "target"

[target.'cfg(target_vendor = "uwp")']
rustflags = ["-C", "link-args=-lOneCore.lib -lWindowsApp.lib"]
